### ISSUE TITLE
Change the library name

### ISSUE THREAD

**Issue by jviotti** [resin-io-playground/node.analytics#3]
The module is tightly coupled to resin, so I believe it should include resin in its name. Also, the `.node` suffix is redundant given the package is pushed to npm. Can we reclaim `resin-analytics`?

**Comment by izavits** [comment]
`resin-analytics` is currently in use. The repo is under `resin-io-modules` and the package has been released to `npm`. We can use maybe another (temporary) name and put this project under the `resin-io-modules` org?

**Comment by jviotti** [comment]
The last commit in `resin-analytics` was last year. You should also take ownership over any analytics library out there, so I still suggest to reclaim `resin-analytics`. You can push your code in `resin-io-modules/resin-analytics` and publish a new major version to npm.
